title: "Yurvan Ramjan's Portfolio"
author: "Yurvan Ramjan"
description: "Showcasing my projects in Machine Learning, Medical Image Analysis, and Quantum Computing."
baseurl: ""  # Leave empty for GitHub Pages
url: "https://yurvanr23.github.io"  # Replace with your GitHub Pages URL
theme: cayman #tactile  # You can choose another theme later if you like
